version: "3.7"

services:
  
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app_gumadesk
      - mysql
    networks:
      - networkapp

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: db_gumadesk
      MYSQL_USER: usr_container
      MYSQL_PASSWORD: pss_container
      MYSQL_ROOT_PASSWORD: db_root_password
    ports:
      - 33069:3306
    volumes:
      - vol_gumadesk:/var/lib/mysql
    networks:
      - networkapp

  app_gumadesk:
    build:
      args:
        user: laraveluser
        uid: 1000
      context: .
      dockerfile: ./Dockerfile
    container_name: app_gumadesk
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - networkapp
    ports:
      - 8081:80

networks: 
  networkapp:

volumes:
  vol_gumadesk: